# Generated by Django 3.1.7 on 2021-03-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome Completo')),
                ('photo', models.ImageField(upload_to='banners')),
            ],
            options={
                'verbose_name': 'Banner',
            },
        ),
    ]
