# Generated by Django 3.1.7 on 2021-03-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orolaser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='banner',
            name='oroClub',
            field=models.IntegerField(default=0, verbose_name='ORO Club'),
        ),
        migrations.AddField(
            model_name='banner',
            name='price',
            field=models.FloatField(default=0, verbose_name='Preço'),
        ),
    ]
