# Generated by Django 3.1.7 on 2021-03-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orolaser', '0002_auto_20210324_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome Completo')),
                ('address', models.CharField(max_length=500, verbose_name='Endereço')),
                ('lat', models.IntegerField(default=0, verbose_name='Latitude')),
                ('long', models.IntegerField(default=0, verbose_name='Longitude')),
                ('photo', models.ImageField(upload_to='imagem')),
                ('opening_hours', models.CharField(max_length=500, verbose_name='Horarios de Funcionamento')),
            ],
            options={
                'verbose_name': 'Unidades',
            },
        ),
    ]
