# Generated by Django 3.1.7 on 2021-03-24 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orolaser', '0003_units'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='units',
            options={'verbose_name': 'Unidade'},
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Nome'),
        ),
    ]
