# Generated by Django 3.1.7 on 2021-03-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orolaser', '0004_auto_20210324_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='lat',
            field=models.FloatField(default=0, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='units',
            name='long',
            field=models.FloatField(default=0, verbose_name='Longitude'),
        ),
    ]
