# Generated by Django 3.1.7 on 2021-03-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orolaser', '0006_notification_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'Notificaçõe'},
        ),
    ]
